# Welcome to Jekyll!

# Website settings
title: "CodeMoneky丶"
description: "Yumwey's blog,use Jekyll and github pages."
keywords: ""
baseurl: "/"
url: "isunmonkey.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Yumwey'
  first_name: 'Yang'
  last_name: 'wei'
  email: '1049818533@qq.com'
  facebook_username: 'no'
  github_username: 'Yumwey'
  avatar: 'static/img/landing/codemonkey.png'
  desc: '入行两年多的一枚前端小菜，在前端这几年的风靡大潮中跌宕起伏，秉着对前端的热爱，抛下了几年.net的学习经验，毅然“下海”，前端是个无底洞，它的发展，没有终章，所以学习，是无止境的事，只有充实自己，方不辜负自己的热爱..'

# localization
languages:
  - locale: 'zh'
    flag: 'static/img/flags/China.png'
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'https://yumwey.github.io/MyFEBlog/static/img/blog'

# donate
donate:
  wechat1: 'static/img/pay/w1.jpeg'
  wechat5: 'static/img/pay/w5.jpeg'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
